repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.5.4'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-case-conflict
- repo: local
  hooks:
  # Not merged with other local repo since we need to run this before poetry.
  # and after lock & check. this will be it's own poetry hook after poetry 1.6.1
  - id: poetry install
    name: Install requirements from pyproject.toml
    entry: poetry install
    language: system
    pass_filenames: false
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
    - id: commitlint
      stages: [ commit-msg ]
      additional_dependencies: ['@commitlint/config-conventional']
